### PR TITLE
Updates for German translation fbb

### PR DESCRIPTION
**Pull request by FBB-de**
Several changes regarding the $:/_fbb/ files. Additional clean-up for duplicate files and incorrectly sorted tiddlers.
Read more in the 2 commits. 

I'm really looking forward to your answer as to whether everything I'm doing here is correct.

### CODE REVIEW

**Comment by pmario** [comment]
Hi Frank, Looks good to me, but I just had a short view. 3 minutes :)    I'll try it later

**Comment by pmario** [comment]
UI, das sind ja mal commit-messages :)
I do like the commit messages. With your comments it's easy to follow, what you thought and why it is as it is. ... 

Yea, we do need to talk about the TOC structure and the "system path settings". .. BUT it looks good.

**Comment by FBB-de** [comment]
Hi Mario, 
... nice if you like it and it is useful :-) 
I am still in the process of rewriting some tiddlers to the new macros. Unfortunately, I also noticed a small error in the new "tipMacros". In the next pull request it will be fixed and hopefully all remnants of the old macros will be removed. After that I will start with the filter operators.

I will call again soon.

**Comment by pmario** [comment]
As long as this PR isn't merged, you can just add commits and push them to the same branch. .. Once you think I should merge it, please tell me.

**Comment by FBB-de** [comment]
@pmario:
Damn, I had just done a pull request on Jerome's master. I hope I was able to soften the blow by closing it right away. How can I correct this now? It can't be pushed to your branch (where it belongs) right now, can it?

**Comment by pmario** [comment]
If you add new commits to your branch, they are automatically listed here. .. See number of changed files. It changed from about 90 to 138 .. so everything seems to be fine

**Comment by FBB-de** [comment]
Ok Mario, if you say so...but I'm not totally confident. Anyway, here is the original text I wanted to write for this commit:
As explained, the changes regarding the new macros (tipMacro and from-verson-de):
Detailed as usual in the commits.

The next step will only be available once I have worked through the existing filter operators.
I have no idea when this should be merged. What is your opinion on this?


Ok. Delete the last two sentences and merge the branch immediately. Then I test immediately afterwards whether I have remembered everything so that I can continue with a new branch.

**Comment by pmario** [comment]
Hi Frank,  grafik

I'd like to have "Neu ab:" instead of "NEU AB:" .. I think it's easier on the eye. ... I know that tiddlywiki.com has it different, but still ...

**Comment by FBB-de** [comment]
> I'd like to have "Neu ab:" instead of "NEU AB:" .. I think it's easier on the eye. ... I know that tiddlywiki.com has it different, but still ...

Ok is noted. If all goes well, I'll report back with the next commit.

**Comment by pmario** [comment]
Be aware that I did merge this branch as requested !!

**Pull request merged**
